### PR TITLE
js2r-require-to-import and js2r-import-to-require

### PR DESCRIPTION
**Pull request by jakoblind**
Hi,

I had the need of converting a lot of require statements to import statements, so I wrote this. Thought it might be useful for others! I was a little bit unsure on where to put the code. I chose js2r-vars.el because a require statement is inside a variable. An option would be to create a new file js2r-imports.el or something similar. 

Unfortunately I haven't been able to write unit tests because I can't run the tests (see https://github.com/magnars/js2-refactor.el/issues/63). When I get tests running, I will write some tests!

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Thanks, but I don't think js2-refactor should handle this kind of refactorings.

@magnars feel free to reopen this if you think otherwise.

**Comment by magnars** [comment]
I have no strong feelings on the matter, since I so rarely use JS these days. But I would be interested to hear what you mean with "this kind" of refactoring. I guess this is a refactoring from a node-style module system to an ES6 module system. Do you think it is too peripheral to the core language?

**Comment by NicolasPetton** [comment]
Magnar Sveen <notifications@github.com> writes:

> I have no strong feelings on the matter, since I so rarely use JS
> these days. But I would be interested to hear what you mean with "this
> kind" of refactoring. I guess this is a refactoring from a node-style
> module system to an ES6 module system. Do you think it is too
> peripheral to the core language?

There are several ways to import packages in JS, and supporting them
feels outside of the scope of this package to me.

**Comment by magnars** [comment]
I think that's fair enough.

**Pull request closed without merging**
