### PR TITLE
ADD: js2r-universal-expand-contract func to work with array,object,func

### PR DESCRIPTION
**Pull request by futurist**
I made this PR since I found it's very useful in my daily usage.

It's just expand and contract closest expression, for array, object, function, function-call

Please review, thanks!

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Thanks for the PR!

I'm not sure about adding another way to expand/contract, while keeping the current ones.
I would rather either 1. stay with what we have or 2. change to what you are suggesting, but then we should remove the current functions.

**Comment by futurist** [comment]
In my daily use I've seldom use the `c a`, `e a` or `c o`, `e o`, instead, using this universal function in most of the case.

In fact, by moving point in the right place, I've use this function for all cases.

**Comment by NicolasPetton** [comment]
> In fact, by moving point in the right place, I've use this function
> for all cases.

Before we replace the previous functions with yours, I'd like to find
better names for them, and better keybindings (what about `js2r-expand-node-at-point'
and `js2r-contract-node-at-point'?).

For consistency, a 2 character keybinding would be great.
I'd also split the function in 2, one for contracting and another one
for expanding, and remove the universal argument.

**Comment by futurist** [comment]
Please review the commit, please suggesting the key binding.

**Comment by NicolasPetton** [comment]
It's nice, thanks! The tests are failing though, could you have a look?

Also, before merging, could you remove the previous functions and keybindings completely, and update the readme?

**Comment by futurist** [comment]
I think the new key-bindings should be carefully choosing, now it's `ee` and `cc`,

below is my suggestions:

1. `ee` and `cc` (easy to remember and press)
2. `ee` and `ec` (e==exp, and press `ee` is very quick)
3. `ne` and `nc` (n==node)
4. `be` and `bc` (b==bracket)

What do you think?

**Comment by futurist** [comment]
Oh, and the version number, I've bumpped a patch version.

But by removing multiple key-bindings, should it be more advanced?

**Comment by NicolasPetton** [comment]
James Yang <notifications@github.com> writes:

> But by removing multiple key-bindings, should it be more advanced?

Yes, it should be a major version bump.

**Comment by futurist** [comment]
Bumpped version into 0.8.0, add docs about the change log.

Also please allow added me to the contributors :smile:

**Comment by NicolasPetton** [comment]
@futurist looks good, thanks! Just squash your commits and we're good to go!

**Comment by futurist** [comment]
please review.

**Comment by NicolasPetton** [comment]
Excellent! :+1: thank you!

**Pull request merged**
