### PR TITLE
Autoload `js2r-rename-var'

### PR DESCRIPTION
**Pull request by nbfalcon**
----

#

### CODE REVIEW

**Comment by NicolasPetton** [comment]
Hey @magnars, are you planning to review and merge these PRs? Otherwise I'd be happy to do it.

**Comment by magnars** [comment]
Hi Nicolas.

Thanks for the heads up. I haven’t coded with JavaScript for at least five
years, so I’m not the right person to maintain this repo.

If you’re able to, that would be great. Thank you so much.

- Magnar

ons. 27. jan. 2021 kl. 20:30 skrev Nicolas Petton <notifications@github.com

**Comment by NicolasPetton** [comment]
@magnars I see, you're one of the lucky ones who get to work all day in Lisp/Clojure? :)

**Comment by magnars** [comment]
Full time Clojure since 2013. :)

ons. 27. jan. 2021 kl. 21:54 skrev Nicolas Petton <notifications@github.com

**Comment by nbfalcon** [comment]
@NicolasPetton @magnars what is the maintainership status of this project? Should I expect my current and future PRs (one to improve iife-wrapping) to be merged anytime soon? If not, I'd like to propose myself as maintainer. I am a reasonably experienced Elisp developer, I think I've written ~4k sloc by now.

**Comment by magnars** [comment]
I'm no longer using JavaScript much, and Nicolas is quite busy, so the repo is in need of some help for sure. Thanks for offering, and welcome as a new maintainer! Cheers! 😊👏

**Comment by nbfalcon** [comment]
@magnars thank you very much! I will be implementing the various issues in the near future, and doing some cleanup.

**Comment by nbfalcon** [comment]
This wont work without further refactoring.

**Comment by NicolasPetton** [comment]
> This wont work without further refactoring.

Why is that?

> Thanks for offering, and welcome as a new maintainer

Awesome! 

@magnars @nbfalcon I don't always have much free time, but I'd like to stay co-maintainer of this project.

**Comment by magnars** [comment]
Most certainly, Nicolas. :) Thanks for pitching in!

lør. 6. mar. 2021 kl. 21:10 skrev Nicolas Petton <notifications@github.com>:

**Comment by nbfalcon** [comment]
@NicolasPetton sorry, in this particular case it actually will; many functions in `js2-mode` depend on `js2-refactor.el` being loaded with its vars available, and can't `require` it because that would result in a circular dependency. I wanted to refactor `js2-refactor` so that each module (`js2-vars`, ...) would be independent, and `require` `js2-refactor` in turn. This way, we would avoid loading the entirety of `js2-refactor` at once and autoloading could be done properly.

**Pull request closed without merging**
