### PR TITLE
`js2r-rename-var`: don't go to start of symbol

### LINKED ISSUE #122: `js2r-rename-var`: don't move cursor to the start of the symbol
```javascript
function xy|zq() {} // | = cursor
```
`js2r-rename-var` then moves the cursor to the start of the symbol, i.e. before `xy`. I think it would be better not to move it.

### PR DESCRIPTION
**Pull request by nbfalcon**
Previously, `js2r-rename-var` would go to the start of the symbol being renamed
first. This makes inserting edits at `point` inconvenient, because one has to
navigate back.

Solve this by first computing a `point`-delta (how far `point` is from the start
of the symbol), and use that to position the other cursors. Don't `goto-char` to
the start of the symbol for the main cursor.

Fixes #122.

----

#

### CODE REVIEW

**Comment by nbfalcon** [comment]
As a side note, why is `js2r-rename-var` not autoloaded?

**Comment by NicolasPetton** [comment]
@nbfalcon There was no reason not to autoload the function, I just added a fix for it.

PS: Do you have write access to this repo now?

**Comment by NicolasPetton** [comment]
@nbfalcon I sort of disagree with the choice here, but I understand that it depends on usages.

**Comment by NicolasPetton** [comment]
@nbfalcon this broke some ecuke tests, I pushed a fix here: https://github.com/magnars/js2-refactor.el/pull/128.

**Comment by nbfalcon** [comment]
@NicolasPetton yes I have write access. Do you think whether `js2r-rename-vars` should keep `point` should be made optional?

**Comment by NicolasPetton** [comment]
> Do you think whether js2r-rename-var should keep point should be made optional?

I'm not sure, I need to experiment a bit more with it.

**Pull request merged**
